
### 회원가입 ( 고객 )
POST http://localhost:8080/signup/customer
Content-Type: application/json

{
  "birth": "1995-09-25",
  "email": "trsoo24@gmail.com",
  "name": "myName",
  "password": "pw",
  "phone": "01012345678"
}

### 이메일 인증 ( 고객 )
GET http://localhost:8080/signup/customer/verify?email=trsoo24@gmail.com&code=FFiOcoWrUI

### 로그인 ( 고객 )
POST http://localhost:8080/signin/customer
Content-Type: application/json

{
  "email": "trsoo24@gmail.com",
  "password": "pw"
}

### 회원 정보 조회 ( 고객 )
GET http://localhost:8080/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJDYUNzdG04VzRzdHF2U1VKSXlSZzRvclZqSmxHM1NQU1ZVOWVxemxUbkxjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzMzMyOTYsImV4cCI6MTY4MDQxOTY5Nn0.ZkNQ4LqoefpVrJyTupwWTnzTgSe1bhg9vrZFqHKLRLs

### 잔액 변경 ( 고객 )
POST http://localhost:8080/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJDYUNzdG04VzRzdHF2U1VKSXlSZzRvclZqSmxHM1NQU1ZVOWVxemxUbkxjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzMzMyOTYsImV4cCI6MTY4MDQxOTY5Nn0.ZkNQ4LqoefpVrJyTupwWTnzTgSe1bhg9vrZFqHKLRLs

{
  "from": "server",
  "message": "잔액 충전",
  "money": 50000
}

###################################

### 회원가입 ( 셀러 )

### 로그인 ( 셀러 )

